name: CICD WITHOUT Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances listées dans requirements.txt

      - name: Run Lint
        run: |
          pip install flake8  # Si vous utilisez flake8 pour l'analyse du code
          flake8 .  # Exécuter flake8 sur le code

      - name: Run Unit Tests
        run: |
          pip install pytest  # Installer pytest si nécessaire
          pytest  # Exécuter les tests avec pytest

  security:
    runs-on: ubuntu-latest
    name: Security Scanning
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          TRIVY_VERSION=0.43.0
          wget "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb"
          sudo dpkg -i "trivy_${TRIVY_VERSION}_Linux-64bit.deb"
          rm "trivy_${TRIVY_VERSION}_Linux-64bit.deb"

      - name: Run Trivy scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Save scan artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: trivy-report.json

  build:
    runs-on: ubuntu-latest
    name: Build App without Docker
    needs: security

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installer les dépendances Python

      - name: Build application
        run: |
          # Suppression de l'étape "python setup.py install"
          echo "Build completed without Docker"  # Cette ligne peut être ajustée selon le besoin de votre projet

  